# 01 Extraction

**Objective**:
To load and inspect the raw dataset and validate its structure,
quality, and suitability for analysis.

In [5]:
import pandas as pd
import numpy as np

In [6]:
df = pd.read_csv("../data/raw/raw_dataset.csv")
df.head()

,FL_DATE,AIRLINE,AIRLINE_DOT,AIRLINE_CODE,DOT_CODE,FL_NUMBER,ORIGIN,ORIGIN_CITY,DEST,DEST_CITY,...,DIVERTED,CRS_ELAPSED_TIME,ELAPSED_TIME,AIR_TIME,DISTANCE,DELAY_DUE_CARRIER,DELAY_DUE_WEATHER,DELAY_DUE_NAS,DELAY_DUE_SECURITY,DELAY_DUE_LATE_AIRCRAFT
0,2021-05-04,JetBlue Airways,JetBlue Airways: B6,B6,20409,384,MCO,"Orlando, FL",JFK,"New York, NY",...,0.0,159.0,152.0,129.0,944.0,NaN,NaN,NaN,NaN,NaN
1,2019-11-26,Delta Air Lines Inc.,Delta Air Lines Inc.: DL,DL,19790,705,FLL,"Fort Lauderdale, FL",DTW,"Detroit, MI",...,0.0,180.0,169.0,150.0,1127.0,NaN,NaN,NaN,NaN,NaN
2,2023-06-18,Southwest Airlines Co.,Southwest Airlines Co.: WN,WN,19393,1926,SMF,"Sacramento, CA",LAS,"Las Vegas, NV",...,0.0,80.0,73.0,59.0,397.0,NaN,NaN,NaN,NaN,NaN
3,2019-07-28,SkyWest Airlines Inc.,SkyWest Airlines Inc.: OO,OO,20304,4459,OKC,"Oklahoma City, OK",DTW,"Detroit, MI",...,0.0,154.0,141.0,122.0,900.0,NaN,NaN,NaN,NaN,NaN
4,2023-03-17,JetBlue Airways,JetBlue Airways: B6,B6,20409,277,FLL,"Fort Lauderdale, FL",SFO,"San Francisco, CA",...,0.0,384.0,402.0,374.0,2584.0,0.0,0.0,18.0,0.0,0.0

In [7]:
print(f"Shape: {df.shape}")
df.info()
df.describe()

Shape: (300000, 32)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300000 entries, 0 to 299999
Data columns (total 32 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   FL_DATE                  300000 non-null  object
 1   AIRLINE                  300000 non-null  object
 2   AIRLINE_DOT              300000 non-null  object
 3   AIRLINE_CODE             300000 non-null  object
 4   DOT_CODE                 300000 non-null  int64
 5   FL_NUMBER                300000 non-null  int64
 6   ORIGIN                   300000 non-null  object
 7   ORIGIN_CITY              300000 non-null  object
 8   DEST                     300000 non-null  object
 9   DEST_CITY                300000 non-null  object
 10  CRS_DEP_TIME             300000 non-null  int64
 11  DEP_TIME                 292292 non-null  float64
 12  DEP_DELAY                292292 non-null  float64
 13  TAXI_OUT                 292168 non-null  float64
 14  WHEELS_OFF               292168 non-null  float64
 15  WHEELS_ON                292047 non-null  float64
 16  TAXI_IN                  292047 non-null  float64
 17  CRS_ARR_TIME             300000 non-null  int64
 18  ARR_TIME                 292048 non-null  float64
 19  ARR_DELAY                291382 non-null  float64
 20  CANCELLED                300000 non-null  float64
 21  CANCELLATION_CODE        7867 non-null    object
 22  DIVERTED                 300000 non-null  float64
 23  CRS_ELAPSED_TIME         299999 non-null  float64
 24  ELAPSED_TIME             291382 non-null  float64
 25  AIR_TIME                 291382 non-null  float64
 26  DISTANCE                 300000 non-null  float64
 27  DELAY_DUE_CARRIER        53521 non-null   float64
 28  DELAY_DUE_WEATHER        53521 non-null   float64
 29  DELAY_DUE_NAS            53521 non-null   float64
 30  DELAY_DUE_SECURITY       53521 non-null   float64
 31  DELAY_DUE_LATE_AIRCRAFT  53521 non-null   float64
dtypes: float64(19), int64(4), object(9)
memory usage: 73.2+ MB

,DOT_CODE,FL_NUMBER,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,TAXI_OUT,WHEELS_OFF,WHEELS_ON,TAXI_IN,CRS_ARR_TIME,...,DIVERTED,CRS_ELAPSED_TIME,ELAPSED_TIME,AIR_TIME,DISTANCE,DELAY_DUE_CARRIER,DELAY_DUE_WEATHER,DELAY_DUE_NAS,DELAY_DUE_SECURITY,DELAY_DUE_LATE_AIRCRAFT
count,300000.000000,300000.000000,300000.000000,292292.000000,292292.000000,292168.000000,292168.000000,292047.000000,292047.000000,300000.000000,...,300000.000000,299999.000000,291382.000000,291382.000000,300000.000000,53521.000000,53521.000000,53521.000000,53521.000000,53521.000000
mean,19976.372630,2513.921653,1327.867817,1330.649303,10.289649,16.658039,1353.234047,1463.544056,7.688304,1491.170703,...,0.002503,142.504398,136.857781,112.523011,811.146313,25.281123,4.229424,13.158685,0.141739,25.411745
std,377.316488,1748.991071,485.717135,499.342287,50.128501,9.193365,500.888860,527.387017,6.310193,511.831883,...,0.049971,71.844714,71.981883,70.059922,590.040227,72.373268,33.590647,33.970947,2.821631,55.600368
min,19393.000000,1.000000,1.000000,1.000000,-62.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,0.000000,18.000000,15.000000,8.000000,30.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,19790.000000,1048.000000,915.000000,917.000000,-6.000000,11.000000,932.000000,1050.000000,4.000000,1109.000000,...,0.000000,90.000000,84.000000,61.000000,379.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,19930.000000,2158.000000,1320.000000,1323.000000,-2.000000,14.000000,1336.000000,1502.000000,6.000000,1518.000000,...,0.000000,125.000000,120.000000,95.000000,655.000000,4.000000,0.000000,0.000000,0.000000,0.000000
75%,20368.000000,3805.000000,1730.000000,1739.000000,6.000000,19.000000,1752.000000,1909.000000,9.000000,1920.000000,...,0.000000,173.000000,168.000000,142.000000,1047.000000,23.000000,0.000000,17.000000,0.000000,29.000000
max,20452.000000,8794.000000,2359.000000,2400.000000,2895.000000,174.000000,2400.000000,2400.000000,217.000000,2359.000000,...,1.000000,695.000000,693.000000,669.000000,5095.000000,2565.000000,1326.000000,1711.000000,221.000000,1514.000000

**Explain:**

- Rows → ~3M (good scale)
- Columns → ~32 (rich dataset)

In [8]:
df.isnull().sum().sort_values(ascending=False)

CANCELLATION_CODE          292133
DELAY_DUE_LATE_AIRCRAFT    246479
DELAY_DUE_SECURITY         246479
DELAY_DUE_NAS              246479
DELAY_DUE_WEATHER          246479
DELAY_DUE_CARRIER          246479
AIR_TIME                     8618
ELAPSED_TIME                 8618
ARR_DELAY                    8618
WHEELS_ON                    7953
TAXI_IN                      7953
ARR_TIME                     7952
TAXI_OUT                     7832
WHEELS_OFF                   7832
DEP_TIME                     7708
DEP_DELAY                    7708
CRS_ELAPSED_TIME                1
ORIGIN_CITY                     0
AIRLINE_DOT                     0
AIRLINE_CODE                    0
DOT_CODE                        0
FL_NUMBER                       0
DISTANCE                        0
ORIGIN                          0
DEST                            0
DIVERTED                        0
CANCELLED                       0
DEST_CITY                       0
CRS_ARR_TIME                    0
AIRLINE                         0
CRS_DEP_TIME                    0
FL_DATE                         0
dtype: int64

**Insight:**

- The cancellation reason (`CANCELLATION_CODE`) and specific delay reason columns (`DELAY_DUE_*`) are highly messy/nullable because they are only recorded when those specific events (cancellations or delays >= 15m) actually happen.
- Actual delay fields (`DEP_DELAY`, `ARR_DELAY`) are occasionally missing, mostly for cancelled or diverted flights.

In [9]:
df.duplicated().sum()

np.int64(0)

### Key Observations:
- Dataset contains missing values in delay columns
- Cancellation data present → useful for KPI
- Time-based columns exist → good for trend analysis